add_test([=[Pentagon.empty_constructor]=]  /home/flaroteur/oop/OOP_3_sem/l3/build1/tests [==[--gtest_filter=Pentagon.empty_constructor]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Pentagon.empty_constructor]=]  PROPERTIES WORKING_DIRECTORY /home/flaroteur/oop/OOP_3_sem/l3/build1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Pentagon.vector_constructor]=]  /home/flaroteur/oop/OOP_3_sem/l3/build1/tests [==[--gtest_filter=Pentagon.vector_constructor]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Pentagon.vector_constructor]=]  PROPERTIES WORKING_DIRECTORY /home/flaroteur/oop/OOP_3_sem/l3/build1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Pentagon.equality]=]  /home/flaroteur/oop/OOP_3_sem/l3/build1/tests [==[--gtest_filter=Pentagon.equality]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Pentagon.equality]=]  PROPERTIES WORKING_DIRECTORY /home/flaroteur/oop/OOP_3_sem/l3/build1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Pentagon.copy]=]  /home/flaroteur/oop/OOP_3_sem/l3/build1/tests [==[--gtest_filter=Pentagon.copy]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Pentagon.copy]=]  PROPERTIES WORKING_DIRECTORY /home/flaroteur/oop/OOP_3_sem/l3/build1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Pentagon.assignment]=]  /home/flaroteur/oop/OOP_3_sem/l3/build1/tests [==[--gtest_filter=Pentagon.assignment]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Pentagon.assignment]=]  PROPERTIES WORKING_DIRECTORY /home/flaroteur/oop/OOP_3_sem/l3/build1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Pentagon.double_cast]=]  /home/flaroteur/oop/OOP_3_sem/l3/build1/tests [==[--gtest_filter=Pentagon.double_cast]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Pentagon.double_cast]=]  PROPERTIES WORKING_DIRECTORY /home/flaroteur/oop/OOP_3_sem/l3/build1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Hexagon.empty_constructor]=]  /home/flaroteur/oop/OOP_3_sem/l3/build1/tests [==[--gtest_filter=Hexagon.empty_constructor]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Hexagon.empty_constructor]=]  PROPERTIES WORKING_DIRECTORY /home/flaroteur/oop/OOP_3_sem/l3/build1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Hexagon.vector_constructor]=]  /home/flaroteur/oop/OOP_3_sem/l3/build1/tests [==[--gtest_filter=Hexagon.vector_constructor]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Hexagon.vector_constructor]=]  PROPERTIES WORKING_DIRECTORY /home/flaroteur/oop/OOP_3_sem/l3/build1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Hexagon.equality]=]  /home/flaroteur/oop/OOP_3_sem/l3/build1/tests [==[--gtest_filter=Hexagon.equality]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Hexagon.equality]=]  PROPERTIES WORKING_DIRECTORY /home/flaroteur/oop/OOP_3_sem/l3/build1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Hexagon.copy]=]  /home/flaroteur/oop/OOP_3_sem/l3/build1/tests [==[--gtest_filter=Hexagon.copy]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Hexagon.copy]=]  PROPERTIES WORKING_DIRECTORY /home/flaroteur/oop/OOP_3_sem/l3/build1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Hexagon.assignment]=]  /home/flaroteur/oop/OOP_3_sem/l3/build1/tests [==[--gtest_filter=Hexagon.assignment]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Hexagon.assignment]=]  PROPERTIES WORKING_DIRECTORY /home/flaroteur/oop/OOP_3_sem/l3/build1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Hexagon.double_cast]=]  /home/flaroteur/oop/OOP_3_sem/l3/build1/tests [==[--gtest_filter=Hexagon.double_cast]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Hexagon.double_cast]=]  PROPERTIES WORKING_DIRECTORY /home/flaroteur/oop/OOP_3_sem/l3/build1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Octagon.empty_constructor]=]  /home/flaroteur/oop/OOP_3_sem/l3/build1/tests [==[--gtest_filter=Octagon.empty_constructor]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Octagon.empty_constructor]=]  PROPERTIES WORKING_DIRECTORY /home/flaroteur/oop/OOP_3_sem/l3/build1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Octagon.vector_constructor]=]  /home/flaroteur/oop/OOP_3_sem/l3/build1/tests [==[--gtest_filter=Octagon.vector_constructor]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Octagon.vector_constructor]=]  PROPERTIES WORKING_DIRECTORY /home/flaroteur/oop/OOP_3_sem/l3/build1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Octagon.equality]=]  /home/flaroteur/oop/OOP_3_sem/l3/build1/tests [==[--gtest_filter=Octagon.equality]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Octagon.equality]=]  PROPERTIES WORKING_DIRECTORY /home/flaroteur/oop/OOP_3_sem/l3/build1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Octagon.copy]=]  /home/flaroteur/oop/OOP_3_sem/l3/build1/tests [==[--gtest_filter=Octagon.copy]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Octagon.copy]=]  PROPERTIES WORKING_DIRECTORY /home/flaroteur/oop/OOP_3_sem/l3/build1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Octagon.assignment]=]  /home/flaroteur/oop/OOP_3_sem/l3/build1/tests [==[--gtest_filter=Octagon.assignment]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Octagon.assignment]=]  PROPERTIES WORKING_DIRECTORY /home/flaroteur/oop/OOP_3_sem/l3/build1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Octagon.double_cast]=]  /home/flaroteur/oop/OOP_3_sem/l3/build1/tests [==[--gtest_filter=Octagon.double_cast]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Octagon.double_cast]=]  PROPERTIES WORKING_DIRECTORY /home/flaroteur/oop/OOP_3_sem/l3/build1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Array.basic_constructor]=]  /home/flaroteur/oop/OOP_3_sem/l3/build1/tests [==[--gtest_filter=Array.basic_constructor]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Array.basic_constructor]=]  PROPERTIES WORKING_DIRECTORY /home/flaroteur/oop/OOP_3_sem/l3/build1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Array.size_conrtuctor]=]  /home/flaroteur/oop/OOP_3_sem/l3/build1/tests [==[--gtest_filter=Array.size_conrtuctor]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Array.size_conrtuctor]=]  PROPERTIES WORKING_DIRECTORY /home/flaroteur/oop/OOP_3_sem/l3/build1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Array.update_element]=]  /home/flaroteur/oop/OOP_3_sem/l3/build1/tests [==[--gtest_filter=Array.update_element]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Array.update_element]=]  PROPERTIES WORKING_DIRECTORY /home/flaroteur/oop/OOP_3_sem/l3/build1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Array.delete_element]=]  /home/flaroteur/oop/OOP_3_sem/l3/build1/tests [==[--gtest_filter=Array.delete_element]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Array.delete_element]=]  PROPERTIES WORKING_DIRECTORY /home/flaroteur/oop/OOP_3_sem/l3/build1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Array.common_surface]=]  /home/flaroteur/oop/OOP_3_sem/l3/build1/tests [==[--gtest_filter=Array.common_surface]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Array.common_surface]=]  PROPERTIES WORKING_DIRECTORY /home/flaroteur/oop/OOP_3_sem/l3/build1 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  tests_TESTS Pentagon.empty_constructor Pentagon.vector_constructor Pentagon.equality Pentagon.copy Pentagon.assignment Pentagon.double_cast Hexagon.empty_constructor Hexagon.vector_constructor Hexagon.equality Hexagon.copy Hexagon.assignment Hexagon.double_cast Octagon.empty_constructor Octagon.vector_constructor Octagon.equality Octagon.copy Octagon.assignment Octagon.double_cast Array.basic_constructor Array.size_conrtuctor Array.update_element Array.delete_element Array.common_surface)
